import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import LogoutNavBarBtn from './components/LogoutNavBarBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en" data-theme="business">
      <body className={inter.className}>
        <nav>
          {!!session && <LogoutNavBarBtn />}
          {!session && <Link href='/login' passHref><button className='btn'>Login</button></Link>}

        </nav>
        <main>
          {children}</main>
      </body>
    </html>
  )
}
