import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import Link from 'next/link'
import LogoutNavBarBtn from './components/LogoutNavBarBtn'
import AuthProvider from './context/AuthProvider'

import NavBar from './components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="business">
      <body className={inter.className}>
      <AuthProvider>
        <NavBar />
        <main>
          {children}
          </main>
          </AuthProvider>
      </body>
    </html>
  )
}
